### ISSUE TITLE
Update screenshot in README

### ISSUE THREAD

**Issue by anderseknert** [srenatus/opa-explorer#12]
To demonstrate the new design:

<img width="649" alt="Screenshot 2023-10-03 at 13 16 26" src="https://github.com/srenatus/opa-explorer/assets/510711/37b09c31-b2d0-4e3a-93cf-6c008cefe054">

I'm kidding of course 😄 And I know you're aware of this since before, but figured I'd post for tracking as I had a good use case for the OPA explorer today again. It's still as useful, just not as pretty.

```
The resource from “https://the.missing.style/missing.css@1.0.3/missing.min.css” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).
```

**Comment by srenatus** [comment]
https://github.com/bigskysoftware/missing/issues/34 must be the upstream issue here. But yeah we could fix it locally.

**Comment by srenatus** [comment]
#13
