### ISSUE TITLE
Allow toggling `print` for inclusion

### ISSUE THREAD

**Issue by anderseknert** [srenatus/opa-explorer#14]
I'm having a lot of issues with print in Regal at the moment, likely related to https://github.com/open-policy-agent/opa/issues/5624

I figured I'd use the opa-explorer to see what the compiler rewrites my code to, but it does not seem to take print into account, and the compiler errors I get from OPA is not reflected here.

**Comment by srenatus** [comment]
https://github.com/srenatus/opa-explorer/issues/5#issuecomment-1378499535

I can't quite remember what I meant here, but maybe it would help? At least it's related, we'd need to add check-boxes for those params. In the mean time, you could hardcode it, perhaps?

**Comment by srenatus** [comment]
_Maybe_ adding `&print=on` here could help:
https://github.com/srenatus/opa-explorer/blob/main/cmd/explorer/main.go#L58

but I'm absolutely not certain about it.

**Comment by srenatus** [comment]
Hardcoding `true` [here](https://github.com/srenatus/opa-explorer/blob/main/cmd/explorer/main.go#L138) should do the trick for sure.

**Comment by anderseknert** [comment]
Thanks. I’ll try it out 😊

**Comment by anderseknert** [comment]
Probably redundant having an issue just for this — we'll want a toggle for anything toggle-able :)
