### ISSUE TITLE
Wrong stage reported for compiler error

### ISSUE THREAD

**Issue by anderseknert** [srenatus/opa-explorer#15]
The "var x is undeclared" error is only emitted in the `rewritePrintCalls` stage, but opa-explorer is reporting it as a `checkVoidCalls` stage error.

![Screenshot 2023-11-03 at 12 58 42](https://github.com/srenatus/opa-explorer/assets/510711/a547e3f8-faf1-4e7c-9d16-0c267023bb2f)

To reproduce:

```rego
package p

allow := {a |
    a := [x | x := input.a[_]][0]
    print(a)
}
```

**Comment by srenatus** [comment]
Probably something amiss here? https://github.com/srenatus/opa-explorer/blob/main/cmd/explorer/main.go#L100-L132 Unfortunately, there's no generic "output stuff after each stage" hook in OPA 😅

**Comment by srenatus** [comment]
Hmm so I've updated OPA (#16), and the stages haven't changed in any way.

**Comment by srenatus** [comment]
Ah, I can see what's wrong: when a stage fails, its after-stage-hooks aren't run:
```go
		c.runStage(s.metricName, s.f)
		if c.Failed() {
			return
		}
		for _, a := range c.after[s.name] {
			if err := c.runStageAfter(a.MetricName, a.Stage); err != nil {
				c.err(err)
				return
			}
		}
```
and I tried accounting for that by setting an overall error to the last stage that ran:
```go
	c.Compile(map[string]*ast.Module{
		"a.rego": mod,
	})
	if len(c.Errors) > 0 {
		result[len(result)-1].Error = c.Errors.Error()
	}
```
but that's the wrong stage -- as you noted, it's the one *before* the one that actually failed 😅

**Comment by anderseknert** [comment]
Nice find! Thanks 😊
